language: node_js
node_js:
- '4'
- '5'
- '6'

branches:
  only:
  - master

before_script:
- npm install
- npm run build

script:
- npm test

after_success:
- bash ./bin/deploy.sh

env:
  global:
  - GH_REF: github.com/KamataRyo/fern.cc.git
